In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("online.csv")

In [3]:
df.head()

   Marketing Spend  Administration  Transport     Area     Profit
0        114523.61       136897.80  471784.10    Dhaka  192261.83
1        162597.70       151377.59  443898.53      Ctg  191792.06
2        153441.51       101145.55  407934.54  Rangpur  191050.39
3        144372.41       118671.85  383199.62    Dhaka  182901.99
4        142107.34        91391.77  366168.42  Rangpur  166187.94

In [4]:
df.shape

(50, 5)

In [6]:
df.isnull().sum()

Marketing Spend    0
Administration     0
Transport          0
Area               0
Profit             0
dtype: int64

In [7]:
x = df.drop(['Profit'],axis=1)
y = df['Profit']

In [9]:
city = pd.get_dummies(x['Area'],drop_first=True)
city

    Dhaka  Rangpur
0    True    False
1   False    False
2   False     True
3    True    False
4   False     True
5    True    False
6   False    False
7   False     True
8    True    False
9   False    False
10  False     True
11  False    False
12  False     True
13  False    False
14  False     True
15   True    False
16  False    False
17   True    False
18  False     True
19   True    False
20  False    False
21   True    False
22  False     True
23  False     True
24   True    False
25  False    False
26  False     True
27   True    False
28  False     True
29   True    False
30  False     True
31   True    False
32  False    False
33  False     True
34  False    False
35   True    False
36  False     True
37  False    False
38   True    False
39  False    False
40  False    False
41  False     True
42  False    False
43   True    False
44  False    False
45   True    False
46  False     True
47  False    False
48   True    False
49  False    False

In [12]:
x = x.drop('Area',axis=1)

   Marketing Spend  Administration  Transport
0        114523.61       136897.80  471784.10
1        162597.70       151377.59  443898.53
2        153441.51       101145.55  407934.54
3        144372.41       118671.85  383199.62
4        142107.34        91391.77  366168.42

In [13]:
x = pd.concat([x,city],axis=1)

In [14]:
x.head()

   Marketing Spend  Administration  Transport  Dhaka  Rangpur
0        114523.61       136897.80  471784.10   True    False
1        162597.70       151377.59  443898.53  False    False
2        153441.51       101145.55  407934.54  False     True
3        144372.41       118671.85  383199.62   True    False
4        142107.34        91391.77  366168.42  False     True

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
reg = LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [18]:
pred = reg.predict(x_test)
pred

array([103041.93019584, 128255.24514289, 126922.75723244,  71221.31157266,
       173705.4106333 , 124824.61560479,  70488.40325151,  98535.73506129,
       116684.02101869, 161845.22370375])

In [19]:
y_test

28    103282.38
11    144259.40
10    146121.95
41     77798.83
2     191050.39
27    105008.31
38     81229.06
31     97483.56
22    110352.25
4     166187.94
Name: Profit, dtype: float64

In [20]:
from sklearn.metrics import r2_score
score = r2_score(y_test,pred)
score

0.8798164664885627